---
name: all_url_check

'on':
  workflow_dispatch:
  push:
  schedule:
    - cron: '25 */3 * * *'

permissions:
  contents: read

jobs:
  run_lychee:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: link_check with lychee-action
        id: link_check
        uses: lycheeverse/lychee-action@01a5c94d8e012550040658854b90a7a7301e75ca # v2.6.0
        with:
          args: --verbose --insecure --no-progress **/*.tex **/*.md
          fail: true
...
