name: check_shell_scripts

on:
  workflow_dispatch:
  push:

jobs:
  check_shell_scripts:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install shellcheck
      run: |
        sudo apt-get install shellcheck
    - name: display shellcheck version
      run: |
        shellcheck --version
    - name: run check_shell_scripts
      run: |
        ./check_shell_scripts.sh
