name: latex_linter_check

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'
jobs:
  latex_linter_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2
