---
name: latex_linter_check

'on':
  workflow_dispatch:
  push:
    paths-ignore:
      - 'generated/**'

permissions:
  contents: read

jobs:
  run_chktex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: LaTeX linter
        uses: colinaaa/chktex-action@5dda098b973d69cdc61ace93fa7bfcef39efaade # v1.1.2
...
